### ISSUE TITLE
Incompatibility with TF 2.1

### ISSUE THREAD

**Issue by sarim-zafar** [cran2367/pca-autoencoder-relationship#1]
I get the following error when i try using the correlation penalty in the dense layer

```ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.```

**Comment by kaanguney** [comment]
The following lines may resolve your issue.
```bash
tf.__version__ # 2.3.0
tf.config.run_functions_eagerly(True) # for value error 
```bash

**Comment by keklikci** [comment]
replacing ```K.eye()``` with ```tf.eye()``` resolved my issue, you could try that out.
